src/AnnotationCommandFactory.php
src/CommandInfo.php

Refactor getargs

---

src/AnnotationCommand.php
src/AnnotationCommandFactory.php
src/CommandInfo.php
src/PassThroughArgsInput.php
tests/src/TestCommandFile.php
tests/testAnnotationCommandFactory.php

Pass command

---

README.md
src/AlterResultInterface.php
src/CommandProcessor.php

Just a start; have not pushed the formatters project yet.

Formatters

---

src/CommandInfo.php

Refactor findMatchingOption.

---

src/AnnotatedCommandFactory.php

This method defaults to true, but may be set to 'false' to require public methods to have a '@command' annotation in order to be considered a command implementation.

Add a new method, setAllPublicMethodsAreCommands()

---

README.md

nothing special. Just added php formatting in sample code for readability. :)

Applying PHP code format in readme

---

CHANGELOG.md
README.md
composer.json
src/AnnotatedCommand.php
src/AnnotatedCommandFactory.php
src/Hooks/HookManager.php
src/Hooks/ProcessResultInterface.php
src/Hooks/ValidatorInterface.php
tests/src/ExampleHookAllCommandFile.php
tests/testAnnotatedCommandFactory.php
tests/testCommandFileDiscovery.php
tests/testFullStack.php

Update the API, since we're doing a 2.x branch.

Annotation data interfaces

---

src/AnnotatedCommand.php
src/AnnotatedCommandFactory.php
src/AutomaticOptionsProviderInterface.php

Add a way for clients to add an automatic options provider to the command factory.

Options providers.

---

CHANGELOG.md
README.md
src/Parser/Internal/AbstractCommandDocBlockParser.php
src/Parser/Internal/CommandDocBlockParser2.php
tests/src/ExampleCommandFile.php
tests/src/alpha/AlphaCommandFile.php
tests/src/beta/BetaCommandFile.php

The type that goes with the option is optional if the $ is present, and must be absent if there is no $.

Make the $ in the option name optional. 

---

composer.lock
src/AnnotatedCommand.php
src/AnnotatedCommandFactory.php
src/Parser/CommandInfo.php
src/Parser/Internal/AbstractCommandDocBlockParser.php
tests/testCommandInfo.php
tests/testFullStack.php

Add a command cache to the command factory.

Command cache

---

src/Parser/CommandInfo.php

Adds the modification date to the cached command info so that we can react when the file is modified.

Rebuild cached command info when commandfile is modified.

---

.travis.yml

Add phpunit 7.1 to test matrix.

Also test on php7.1.

---

composer.lock
tests/testAnnotatedCommandFactory.php

Test to show that -- is working correctly with --version. This is a bug in Symfony/Console 2.x, fixed in 3.x.

Add a test for Symfony 2.x double-dash bug.

---

src/Parser/CommandInfo.php

Serialize / deserialize functions were too complicated, and had duplicate code. Simplified.

Simplify the serialize / deserialize functions of CommandInfo.

---

src/Help/HelpDocument.php

Used by Drush at https://github.com/drush-ops/drush/pull/2670. May be useful to future custom help implementations

Unprotect two methods for benefit of Drush help.

---

CHANGELOG.md
README.md
tests/src/alpha/AlphaCommandFile.php

Better information about various hook annotations.

Fixes #110 and #111: provide better documentation for hook functions.

---

src/AnnotatedCommand.php
src/Parser/CommandInfo.php

Add support for @hidden. Requires Symfony 3.2+.

Add support for @hidden. Requires Symfony 3.2+.

---

.gitattributes
.travis.yml
LICENSE
composer.json
composer.lock
scenarios/install
scenarios/phpunit4/composer.json
scenarios/phpunit4/composer.lock
scenarios/symfony2/composer.json
scenarios/symfony4/composer.json
scenarios/symfony4/composer.lock

Update to composer test scenarios ^2.

---

README.md
src/AnnotationData.php

Attempt to add a setter to the AnnotationData class.
See #173

Naiive attempt to add a setter.

---

.travis.yml
composer.json
composer.lock

Remove older dependencies and older PHP versions.

Create the 3.x version (on master branch)

---

.scenarios.lock/symfony4/composer.json
.scenarios.lock/symfony4/composer.lock
.travis.yml
LICENSE
appveyor.yml
composer.json
composer.lock
src/Input/StdinHandler.php

Test with PHP 7.4.

---

README.md

Fixed typo in readme file.

---

.github/workflows/ci.yml
composer.json
composer.lock
src/CommandLineAttributes.php
src/Parser/Internal/AttributesDocBlockParser.php
src/Parser/Internal/CommandDocBlockParserFactory.php
tests/AttributesCommandFactoryTest.php
tests/CommandFileDiscoveryTest.php
tests/CommandInfoTest.php
tests/src/ExampleAttributesCommandFile.php

- Adds a feature - [Adds support providing command information via php8 Attributes](https://github.com/consolidation/annotated-command/issues/215).
- Has tests that cover changes
Any additional information.

Add support for providing command information via php8 Attributes.

---

.github/workflows/ci.yml
.gitignore
README.md
src/AnnotatedCommand.php
src/CommandData.php
src/Parser/CommandInfo.php
src/Parser/DefaultsWithDescriptions.php
src/Parser/Internal/BespokeDocBlockParser.php
src/Parser/Internal/DefaultValueFromString.php
tests/AnnotatedCommandFactoryTest.php
tests/src/ExampleCommandFile.php

Backport of #224 to 4.x branch.

First class options backport

---

.github/workflows/ci.yml

Re enable b c checks

---

.gitignore
src/Parser/Internal/AttributesDocBlockParser.php
tests/AttributesCommandFactoryTest.php
tests/src/ExampleAttributesCommandFile.php

Updating the attributes processor to work with flexible options. As a side effect, we clean up the code a little bit.

Allow flexible options to work with the attributes processor.

---

src/Parser/CommandInfo.php

Backport simple option parameters fix for bc break

---

src/AnnotatedCommandFactory.php

Less parsing by ignoring Traits and IO.php (for Drush) (#237)

---

CHANGELOG.md
src/AnnotatedCommandFactory.php

Add switch for trait optimization

---

src/AnnotatedCommand.php

Needed for https://github.com/drush-ops/drush/pull/4931

Make addUsageOrExample() public

---

.github/workflows/ci.yml
composer.json
composer.lock
src/AnnotatedCommand.php
src/CommandData.php
tests/AnnotatedCommandFactoryTest.php
tests/HelpTest.php

Compatibility with Symfony 5.2+ (#249)

---

composer.json
composer.lock

Support Symfony 6 (#250)

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
src/AnnotatedCommandFactory.php

Forward-port switch from 4.x, but default to not searching in Traits.

Set ignore commands

---

src/CommandProcessor.php

Not going to update this branch to test on PHP 8, just trying to fix some problems evidenced in Drush 8's usage.

Update call_user_func_array for php 8

---

src/CommandResult.php

Issue #258 - CommandResult inheritance

Issue #258 - CommandResult inheritance

---

src/CommandResult.php

Issue #258 - CommandResult inheritance
This is already fixed in the `main` branch, but this PR for the `4.x` branch.

Issue #258 - 4.x - CommandResult inheritance

---

src/Attributes/Help.php

Short overview of what changed.
Any additional information.

Only send a string to setHelp() and a bool to setHidden()

---

src/AnnotatedCommand.php

Guard nulls
