consolidation/annotated-command

src/AnnotationCommand.php, src/AnnotationCommandFactory.php, tests/src/TestCommandFile.php, tests/testAnnotationCommandFactory.php
This allows easy passing of $input and $output, should a legacy command desire it.
=> Allow InputInterface and OutputInterface as special parameters

src/AlterResultInterface.php, src/AnnotationCommand.php, src/AnnotationCommandFactory.php, src/CommandError.php, src/CommandInfo.php, src/CommandProcessor.php, src/ExtractOutputInterface.php, src/HookManager.php, src/OutputDataInterface.php, src/StatusDeterminerInterface.php, src/ValidatorInterface.php, tests/src/TestCommandFile.php, tests/testAnnotationCommandFactory.php
Recognize @hook annotations to indicate that a method is a hook, not a command.
=> Command hooks

src/AnnotationCommandFactory.php, src/CommandCreationListenerInterface.php, src/CommandProcessor.php
The creation listener is utilized by the bootstrap manager, to give it an opportunity to do dependency injection of the bootstrap object on bootstrap-aware commands. This is only necessary if this is not already being injected via dependency injection inflectors.
=> Creation listener

src/AnnotationCommandFactory.php, src/HookManager.php, src/ProcessResultInterface.php
Add a new PROCESS hook. Works the same as ALTER_RESULT, but happens first. Gives clients an extra place to add hooks to convert results e.g. from a list of tasks into a result object, without mixing these hooks with result-altering hooks.
=> Process hook

composer.json, src/AnnotationCommandFactory.php, src/CommandFileDiscovery.php, tests/src/TestCommandFile.php, tests/src/alpha/AlphaCommandFile.php, tests/src/alpha/Exclude/ExcludedCommandFile.php, tests/src/alpha/Include/IncludedCommandFile.php, tests/src/beta/BetaCommandFile.php, tests/src/beta/IgnoredCommandFile.php, tests/testCommandFileDiscovery.php
Implementation of a basic discovery class. Finds named commandfiles and keeps track of what namespace they are expected to be in.
=> Add CommandFileDiscovery class.

src/AnnotatedCommand.php, src/CommandDocBlockParser.php, src/CommandInfo.php, tests/testCommandInfo.php
Remove CommandInfo wrappers around DefaultsWithDescriptions (arguments and options) objects.
=> Simplify CommandInfo class.

src/Parser/CommandDocBlockParser.php, tests/src/ExampleAnnotatedCommand.php
For use when annotating the execute() method.
=> Add @arg as a synonym for @param

README.md, tests/src/ExampleAnnotatedCommand.php, tests/src/ExampleCommandFile.php, tests/testAnnotatedCommand.php, tests/testAnnotatedCommandFactory.php
Pedantic spelling change for concatenate.
=> Pedantic PR - Correct concatenate spelling

src/AnnotatedCommand.php, src/AnnotationData.php, src/CommandProcessor.php, src/Hooks/HookManager.php, src/Parser/CommandInfo.php, tests/src/ExampleCommandFile.php, tests/testAnnotatedCommandFactory.php
Allows commands tagged with arbitrary annotations to use same for hooks.
e.g. `@hook pre-validate @authenticate` to run the hook function that follows on any command tagged `@authenticate` during the pre-validate phase.
=> Annotation hooks

src/AnnotatedCommand.php, src/AnnotatedCommandFactory.php, src/Hooks/HookManager.php, tests/src/ExampleHookAllCommandFile.php, tests/testAnnotatedCommandFactory.php, tests/testCommandFileDiscovery.php
Hooks with no command name are those in the form:
```
@hook alter
```
Instead of:
```
@hook alter my:command
```
These now apply to all commands defined in the same class, rather than to some command elsewhere that happens to have the same method name.
Hooks with no command name are probably rare-to-nonexistent.  All the same, this is being treated as a breaking change.
=> Change the meaning of hooks with no command name.

src/AnnotatedCommand.php, src/Parser/CommandInfo.php, src/Parser/Internal/AbstractCommandDocBlockParser.php, tests/src/ExampleCommandFile.php, tests/testAnnotatedCommandFactory.php
Ensure that @command annotation with command name is always available in annotated data provided to hooks.
=> Provide @command name to hooks

.gitignore, README.md, src/AnnotatedCommand.php, src/CommandProcessor.php, src/Hooks/HookManager.php, src/Hooks/InitializeHookInterface.php, src/Hooks/InteractorInterface.php, tests/src/ExampleCommandFile.php, tests/testAnnotatedCommandFactory.php
Rename the Symfony Command Event hook to the 'Command Event Hook', and introduce our own 'Command' hook that will run before and after the main command hook ('pre-command' and 'post-command', respectively). Also add an 'initialize' hook, for supplying input options from configuration files, etc.
=> Improve structure of some of the hooks

README.md, src/AlterOptionsCommandEvent.php, src/AnnotatedCommand.php, src/AnnotatedCommandFactory.php, src/CommandProcessor.php, src/Hooks/HookManager.php, src/Hooks/OptionHookInterface.php, src/Parser/CommandInfo.php, src/Parser/DefaultsWithDescriptions.php, tests/src/alpha/AlphaCommandFile.php, tests/testAnnotatedCommandFactory.php, tests/testFullStack.php
This allows hooks to add @option and @usage annotations that will be attached to the help text of the command(s) they hook.
See https://github.com/drush-ops/drush/issues/2336
=> Hook options

src/AnnotatedCommand.php, src/AnnotatedCommandFactory.php, src/Parser/CommandInfo.php, tests/testAnnotatedCommandFactory.php
Rename getAnnotations() to getRawAnnotations(), and getAnnotationsForCommand() to getAnnotations().
=> Better name for getAnnotations() methods

src/AnnotatedCommandFactory.php, src/AnnotationData.php, src/CommandInfoAltererInterface.php, src/Parser/CommandInfo.php, tests/src/ExampleCommandFile.php, tests/src/ExampleCommandInfoAlterer.php, tests/testAnnotatedCommandFactory.php
Provide a hook to allow commandinfo to be altered just before an annotated command is created.
=> CommandInfo alter hook

src/AnnotatedCommandFactory.php, tests/src/alpha/AlphaCommandFile.php, tests/testFullStack.php
Allow command methods annotated with @command to be treated as commands, even if their method names look like an accessor.
=> Fix commands that look like accessors

README.md, composer.json, composer.lock, src/CommandProcessor.php, src/Options/PrepareFormatter.php, src/Options/PrepareTerminalWidthOption.php, tests/src/ApplicationWithTerminalWidth.php, tests/src/alpha/AlphaCommandFile.php, tests/testFullStack.php
Support output formatter wordwrapping.
Provide a class to pass the terminal width from the Symfony Console Application object to the FormatterOptions object that needs it.  Set this up via dependency injection, so that clients can alter the behavior as needed.
=> Support output formatter wordwraping.

composer.json, composer.lock, src/CommandProcessor.php, tests/testFullStack.php
'pipe' option not working right in Drush
=> Make CommandProcessor::getFormat() call FormatterOptions::getFormat().

composer.json, composer.lock, src/AnnotatedCommand.php, src/Help/HelpCommand.php, src/Help/HelpDocument.php, src/Help/HelpDocumentAlter.php, src/Parser/CommandInfo.php, src/Parser/Internal/AbstractCommandDocBlockParser.php, tests/src/alpha/AlphaCommandFile.php, tests/testHelp.php
Symfony Console's help command does not render usages, examples, aliases and topics the way we'd like it to.  We'd also like to add wordwrapping. In progress.
Implement xml and json formats for custom help command. Still needs txt and md formats. Also, currently defined as my-help; must be able to use it to replace actual Symfony help command.
=> Custom help command

src/AnnotatedCommand.php, src/Parser/CommandInfo.php, src/Parser/Internal/AbstractCommandDocBlockParser.php, tests/src/alpha/AlphaCommandFile.php, tests/testHelp.php
Renamed `@topic` annotation to `@topics`
The `@topics` annotation was added specifically for Drush; however, the initial implementation was wrong, as Drush uses `@topics`, and `@topic` was used here. So, this PR fixes that bug in the initial implementation. This would break anyone who relied on the buggy behavior. There shouldn't be anyone, but if there is, they should change to adapt to use `@topics`.
The `@topic` annotation is used to identify commands that are topics, so they can be collected and listed by the `topic` command.
=> Bugfix: Rename @topic annotation to @topics for compatibility with Drush

src/CommandFileDiscovery.php
The existing code in CommandFileDiscovery::discover() fails if namespaces end with a \.
Packagist requires namespaces in autoload psr-4 sections to end with a trailing \. However, if the various CommandFileDiscovery `discover` methods end in a backslash, then discovery fails. With this PR, we accept namespaces both ways, without the trailing \ to maintain backwards compatibility with existing annotated-command clients, and with the trailing \ for clients that wish to take namespaces from a composer.json autoload section and pass them to the discovery class.
=> Robustly handle trailing delimiters in CommandFileDiscovery.

README.md
Fixing a broken link in README.md
=> Broken link fix for "Robo as a framework"

composer.lock, src/AnnotatedCommand.php, src/AnnotatedCommandFactory.php, src/Parser/CommandInfo.php, src/Parser/Internal/AbstractCommandDocBlockParser.php, tests/testCommandInfo.php, tests/testFullStack.php
Add `serialize` and `deserialize` capabilities to CommandInfo objects to allow clients to cache command info.
=> Provide a mechanism to serialize and deserialize CommandInfo

src/Parser/Internal/AbstractCommandDocBlockParser.php, tests/testAnnotatedCommandFactory.php
Description is omitted on the last argument if the command has no options.
See #70.
This is a failing test; fix forthcoming.
=> Bug #70: Fix argument help for last item

src/Hooks/HookManager.php, src/Parser/CommandInfo.php, tests/testAnnotatedCommandFactory.php
Store the path to the commandfile in the CommandData object.
The purpose here is to facilitate a plugin manager's ability to locate the autoload file for a given plugin.
=> Provide path to command file in AnnotationData objects.

README.md, src/Parser/CommandInfo.php, tests/src/ExampleAnnotatedCommand.php, tests/src/ExampleCommandFile.php, tests/testAnnotatedCommand.php, tests/testAnnotatedCommandFactory.php
This pr allows to pass an option with multiple arguments
This commands will produce
```bash
frol-mbp@vagrant:/path$ robo parallel:run -t 10 -s api -s acceptance
frol-mbp@vagrant:/path$ robo parallel:run -t 10 --suite=api --suite=acceptance
#Above commands will produce:
array(11) {
["threads"]=>
string(2) "10"
["suite"]=>
array(2) {
[0]=>
string(3) "api"
[1]=>
string(10) "acceptance"
}
...
frol-mbp@vagrant:/path$ robo parallel:run-test -h
Usage:
parallel:run-test [options]
parallel:run-test -t 5 -s api
Options:
-t, --threads=THREADS                Number of threads to use for running the tests
-s, --suite=SUITE                    Suite to run tests (multiple values allowed)
-h, --help                           Display this help message
-q, --quiet                          Do not output any …
```
=> 77 array option support

src/AnnotatedCommandFactory.php, src/Cache/CacheWrapper.php, src/Cache/NullCache.php, src/Cache/SimpleCacheInterface.php, src/Parser/CommandInfo.php, src/SimpleCacheInterface.php, tests/src/InMemoryCacheStore.php, tests/testAnnotatedCommandFactory.php
Add a documentation interface for the cache storage object for clarity.
=> Add SimpleCacheInterface as a documentation interface (not enforced).

CHANGELOG.md, src/CommandProcessor.php, src/Hooks/Dispatchers/CommandEventHookDispatcher.php, src/Hooks/Dispatchers/ExtracterHookDispatcher.php, src/Hooks/Dispatchers/HookDispatcher.php, src/Hooks/Dispatchers/InitializeHookDispatcher.php, src/Hooks/Dispatchers/InteractHookDispatcher.php, src/Hooks/Dispatchers/OptionsHookDispatcher.php, src/Hooks/Dispatchers/ProcessResultHookDispatcher.php, src/Hooks/Dispatchers/StatusDeterminerHookDispatcher.php, src/Hooks/Dispatchers/ValidateHookDispatcher.php, src/Hooks/HookManager.php
The hook manager class was too large; removed the responsibility of hook dispatching from it for better maintainability.
Note that this PR removes public methods from the HookManager; however, this change is not considered to be a significant backwards-compatibility break, as no client should call these methods.
=> Factor hook dispatchers out of the HookManager class.

src/AnnotatedCommandFactory.php, src/Parser/CommandInfo.php, src/Parser/CommandInfoDeserializer.php, src/Parser/CommandInfoSerializer.php, src/Parser/DefaultsWithDescriptions.php, tests/src/ExampleCommandFile.php, tests/testAnnotatedCommandFactory.php, tests/testCommandInfo.php
Command options were losing their default values after being cached, and restored from the cache.
=> Ensure that the default value of options are correctly cached.

src/AnnotatedCommandFactory.php, src/Parser/CommandInfo.php, src/Parser/CommandInfoDeserializer.php, src/Parser/CommandInfoSerializer.php
Previous release optimized the commandfile cache, removing unneeded entries for methods that were not hooks or commands. Unfortunately, this added a significant amount of overhead to the restore-from-cache code path, as the un-cached methods needed to be parsed again, just to determine that they are not hooks or commands.
To fix this, we store a placeholder entry in the cache indicating that the method is invalid.
=> Ensure that placeholder entries are written into the commandfile cache.

composer.json, composer.lock
Avoid https://github.com/symfony/symfony/issues/22050
Avoid latest version of Symfony Console until bug is fixed.
=> Pin Symfony Console to < 3.2.5 

src/Parser/CommandInfo.php, tests/testAnnotatedCommandFactory.php
This is important for 'list --format=raw'.
`list --format=raw` contains unnecessary / incorrect line breaks if the help description contains any line breaks. This PR ensures that will never happen.
=> Ensure that the help text description never wraps

composer.json, composer.lock, tests/testAnnotatedCommandFactory.php
The Symfony/Console pin is causing more problems than the bug it is avoiding. Pin Symfony Console to version 3.2.4 in your application if validation of options with required values is important.
Composer sometimes resolved this pin as intended: allow annotated-command 2.4.7, and pin Symfony/Console to 3.2.4.  However, at other times it would allow Symfony/Console to go to version 3.2.6, and would instead pin annotated-command to version 2.4.5. Since the behavior is unpredictable, it is better to just remove the pin from this project.
=> Remove Symfony/Console pin

appveyor.yml, composer.json, composer.lock, src/Options/PrepareTerminalWidthOption.php, tests/src/TestTerminal.php, tests/testFullStack.php, tests/testHelp.php
WordWrap is now automatically disabled when stdout is not connected to a terminal.
Prior to this change, `myapp | grep regex` could be subject to random failures or strange truncated results if the output is longer than the terminal width, as word wrapping was being done regardless of whether or not stdout was directed at a terminal.
This PR disables wordwrap by default when stdout is redirected.
=> Automatically disable wordwrap when the terminal is not connected to STDOUT

src/Options/PrepareTerminalWidthOption.php
… based on whether or not stdout has been redirected. Use '--format=tsv' to avoid wrapping in scripts.
=> Do not change word-wrapping behavior

composer.json
Allow phpdocumentor/reflection-docblock 4
=> Allow phpdocumentor/reflection-docblock 4

README.md, src/AnnotatedCommand.php, src/CommandData.php, tests/src/ExampleCommandFile.php, tests/testAnnotatedCommandFactory.php
Currently handling of `InputInterface` & `OutputInterface` arguments is broken, so this PR fixes it.
The feature doesn't work at all now, seems that nobody has used it before.
=> Symfony IO parameters fix

CHANGELOG.md, src/CommandFileDiscovery.php
Adds a new method `followSymlinks()` that causes discovery class to follow symlinks.
=> Follow symlinks

CHANGELOG.md, README.md, src/CommandData.php, src/Parser/CommandInfo.php, tests/src/ExampleCommandFile.php, tests/testAnnotatedCommandFactory.php
This allows us to improve the handing of options which may or may not have been specified by the user on the commandline.
Instead of `'foo' => null` (which did not produce correct results), applications should now instead use `'foo' => InputOption::VALUE_OPTIONAL`.
Paraphrased from the README:
The special value InputOption::VALUE_OPTIONAL produces the following behavior:
- If the option is given a value (e.g. `--foo=bar`), then the value will be a string.
- If the option exists on the commandline, but has no value (e.g. `--foo`), then the value will be `true`.
- If the option does not exist on the commandline at all, then the value will be `false`.
LIMITATION: If any Input object other than ArgvInput (or a subclass thereof) is used, then the value will be `null` unless …
=> Replace default option value of 'null' with InputOption::VALUE_OPTIONAL

CHANGELOG.md, README.md, src/AnnotatedCommand.php, src/CommandData.php, src/Parser/CommandInfo.php, tests/src/ExampleCommandFile.php, tests/testAnnotatedCommandFactory.php
Options may now have a default value of `true`.
See updated description in README.
=> Support special option default value of 'true'.

.travis.yml, CHANGELOG.md
Versions in the 2.5.x range were not sufficiently backwards-compatible with the 2.x line of Annotated Command, breaking some users.  This release rolls back those changes.
=> Update CHANGELOG for 2.6.0 release.

CHANGELOG.md, README.md, src/CommandData.php, src/Parser/CommandInfo.php, tests/testAnnotatedCommandFactory.php
This time, ensure that the 'missing' value for options with optional values that are not included on the commandline remains 'null'. This should preserve backwards compatibility.
See description in README
=> Bring back the features from the 2.5.x branch

src/AnnotatedCommandFactory.php, tests/src/alpha/AlphaCommandFile.php
Allegedly, public static methods in a commandfile produce an invalid CommandInfo structure with an empty command name, crashing Symfony Console.  This PR attempt to define a failing test, and then fix it. However, the test does not identify the problem (all tests pass, when in theory some should fail).
Fixes https://github.com/drush-ops/drush/issues/2919
=> Command method and name checks

src/Parser/CommandInfo.php, tests/src/ExampleCommandFile.php, tests/testAnnotatedCommandFactory.php
`$options = []` is now allowed as the last parameter of an annotated command function.
This behavior was inherited from the original annotation code in Robo, which assumed that there was no point in declaring the `$options` parameter for command scripts that have no options. However, some commands may not have any locally-defined options, but may still want access to the `$option` variable for the purpose of reading global options, options injected from an annotation hook, etc.
This PR allows this scenario to work.
=> Allow $options parameter to be empty.

.travis.yml, composer.json, composer.lock
Add Symfony 4 components to composer.json, and update Travis matrix to test all three versions of Symfony.
=> Allow Symfony 4 components and add tests for three versions of Symfony.

src/CommandData.php
The CommandData class is too indiscriminate about removing the command name.
=> Fixes #139: Do not shift off the command name unless it is there.

src/CommandFileDiscovery.php
Adds support for project names with '-' and path components such as "custom" and "contrib"
When managing plugins / extensions with Composer, and placing them via Composer Installers, there will be additional directories placed by Composer that we need to account for when finding commandfiles.
For example, Drush has the following recommended installer path:
```
"drush/Commands/contrib/{$name}": ["type:drupal-drush"]
```
If the Composer project has a name similar to `my-cool-plugin`, then the old discovery code would
produce a namespace that included dashes, and that included the `contrib` portion of the path. Both
of these things are undesirable. PHP namespaces cannot contain dashes, and if the namespace in
the plugin contains "contrib", then it would not be possible to …
=> Improve commandfile discovery for extensions installed via Composer.

src/CommandProcessor.php, src/CommandResult.php, tests/FullStackTest.php, tests/src/alpha/AlphaCommandFile.php, tests/src/beta/BetaCommandFile.php
CommandResult allows a command to return a result that contains both an exit code and data (e.g. RowsOfFields et. al.)
The existing API allows applications to define custom data types that may represent both an exit code and result data. This PR provides a standard class with this capability.
=> Add a new data type, CommandResult

src/Parser/Internal/BespokeDocBlockParser.php, tests/AnnotatedCommandFactoryTest.php, tests/src/ExampleCommandFile.php
This PR fixes a bug where the inclusion of `@param InputInterface $input` (to satisfy linters) breaks the command arguments.
=> Fix commands that have a @param annotation for their InputInterface/OutputInterface params

CHANGELOG.md, src/Parser/Internal/BespokeDocBlockParser.php, tests/src/ExampleCommandFile.php
Allow option default values to be defined inside the description for the option's annotation, as in:
```
@option $foo A foo field. Default: bar
```
=> Default shorthand

tests/AnnotatedCommandFactoryTest.php, tests/AnnotatedCommandTest.php, tests/FullStackTest.php, tests/FullyQualifiedClassCacheTest.php, tests/HelpTest.php
- Removing unused namespace declaring  because they're unused.
- It seems that these namespaces
=> Remove unused namespace declaring

composer.json, composer.lock
Allow Symfony `^5` on:
- symfony/console
- symfony/event-dispatcher
- symfony/finder
#SymfonyHackday
=> allow symfony 5

src/AnnotatedCommand.php, src/CommandProcessor.php, src/Hooks/Dispatchers/CommandEventHookDispatcher.php, src/Hooks/Dispatchers/InitializeHookDispatcher.php, src/Hooks/Dispatchers/InteractHookDispatcher.php, src/Hooks/Dispatchers/ProcessResultHookDispatcher.php, src/Hooks/Dispatchers/ValidateHookDispatcher.php, src/InjectionHelper.php, src/Output/OutputAwareInterface.php
Robo command files are harder to test than they should be, because the DI container caches $input and $output and provides the cached value to the command object, which actually needs / wants the $input and $output parameters provided to the Symfony command object.
This PR re-injects the fresh values to ensure that the correct result is obtained.
=> Inject $input and $output into the command instance if it is set up to receive them.

src/Parser/CommandInfo.php
Prepare for php 8 https://php.watch/versions/8.0/deprecated-reflectionparameter-methods
The methods that I use for substitution are available since php 7 so there shouldn't be any problem
=> Address deprecation of ReflectionType::getClass()

src/AnnotatedCommandFactory.php, tests/AnnotatedCommandFactoryTest.php, tests/src/ExampleCommandFile.php
Move the alter for command info to earlier moments of the life
of the object.
Add the concept of the @ignored-command annotation as a quick and handy way to remove a method to be recognized as a command.
Initially discussed here
https://github.com/consolidation/Robo/pull/987
As an additional change I moved the alter of the $commandInfo to the earliest moment possible. This has the potential to break things but I think it is pretty safe. This is needed for detecting later a dynamically added `@ignored-command` annotation. I plan to use a CommandInfoAlterer in Robo to add the annotations.
The confusing part was the `createCommandInfo` method as it seems to be only used by the tests and is some kind of alias for the `CommandInfo::create()` method. Its presence doesn't make …
=> Add @ignored-command annotation.

src/AnnotatedCommandFactory.php, tests/AnnotatedCommandFactoryTest.php, tests/src/ExampleCommandFile.php
Add a list of regular expressions to AnnotatedCommandFactory that are going to be matched against the method names of the class with the commands. When the method name matches that method won't be considered a command.
The discussion started here:
https://github.com/consolidation/Robo/pull/987
I deprecated a couple of methods and made non-static protected copies of them.
=> Add ability to ignore methods using regular expressions.

src/Parser/CommandInfo.php
Only allow simple option parameters if the final options-array parameter is NOT used (fix bc break).
See https://github.com/drush-ops/drush/issues/4813 for details.
=> Fix bc break with simple option parameters

src/AnnotatedCommandFactory.php
Avoid repeated parsing of methods unlikely to contain annotations.
=> Fix #234. Less parsing by ignoring Traits and IO.php 

.github/workflows/ci.yml, composer.json, composer.lock, src/AnnotatedCommand.php, src/CommandData.php, tests/AnnotatedCommandFactoryTest.php, tests/HelpTest.php
I see many unfinished attempts to implement compatibility with Symfony 5.2+.
I didn't start from scratch, but reused changes implemented by @boedah in #220 and @mkilmanas in #218
I took into account comment that `getNativeDefinition()` can't be used because it isn't part of public API,
so I deconstructed InputOption object and passed parameters to `addOption` method instead,
And fixed HelpTest to support option description changes implemented in symfony/console 5.2.0 and 5.3.0
=> Compatibility with Symfony 5.2+

composer.json, composer.lock, tests/HelpTest.php
No breaking changes were introduced by Symfony 6.
One test failed because of this change in consolidation/output-formatters library, so I fixed it.
https://github.com/consolidation/output-formatters/commit/4ede6b9084e697d3eef122eca4aab0e1be549e91
=> Support Symfony 6

src/AnnotatedCommand.php
Forward-ported from 4.x branch
=> Do not pass null to Symfony Command methods

src/Parser/CommandInfo.php
Do not call isBuiltin() unless the reflection type is the right kind of reflection type subclass (avoid no-such-method errors).
=> Fix isBuiltin() edge case
